name: Inject Token

on:
  push:
    branches:
      - main

jobs:
  inject-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Inject GitHub Token into HTML
        run: |
          sed -i "s/ghp_你的token/${{ secrets.GITHUB_API_TOKEN }}/g" index.html
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
